### ISSUE TITLE
ARRR LITE WALLET CONNECTION ISSUES  Possibly a BUG

### ISSUE THREAD

**Issue by Tracex-sys** [PirateNetwork/PirateWallet-Lite#101]
Arrr Pirate.black Can't access my account Connection error/ Error: failed to fill whole buffer.

Charles Swank here; I can't access my ARRR Lite Wallet account. Problem is a connection error, Error: "failed to fill whole buffer." I have recovery seed. No matter what I try to do to recover ARRR account according to instructions, the error, the failure to FILL WHOLE BUFFER status is preventing me from getting full access to my ARRR ACCOUNT.

I was able to recover my ARRR ACCOUNT before and didn't have any problems as I do know.

Please advise

Charles Swank
![Screenshot_802](https://user-images.githubusercontent.com/65625306/204400065-56c8ec3b-6752-4654-8a11-903ba1a79df9.png)

**Comment by sailorjerry58** [comment]
I am having this same Issue.  Has there been a fix disclosed yet?

**Comment by CryptoForge** [comment]
update to the newest version
