### ISSUE TITLE
NO CONNECTION TO PIRATE NETWORK  PIRATE CHAIN WALLET-LITE v 1.0.6  CAN'T ACCESS MY WALLET

### ISSUE THREAD

**Issue by Tracex-sys** [PirateNetwork/PirateWallet-Lite#103]
Support, Charles Swank here; Please read the following:

Pirate chain wallet-lite v 1.0.6 no connection: Charles Swank here; I have been directed to go here and go there for instructions
on "HOW TO RECONNECT Pirate chain wallet-lite v 1.0.6 for a week now and still no resolve. I am not a tech person so I don't understand the tech jargon, does that make sense? That is why I need step by step instructions to reconnect my wallet from somebody that knows their stuff. Giving me a computer generated script to follow is not going to work (TECH GARGON). I need instructions from some one that will take the time to guide me in laymen terms. Pirate Chain's FAQ "GENERAL QUESTIONS" does not ask the question, "How do you reconnect Pirate chain wallet-lite v 1.0.6 when I a receive a prompt that displays "NO CONNECTION!" I did loose my connection to my wallet and when I click the Pirate Chain thumb nail, the web page appears and the box in the upper left corner of the page. In that box, I click "RESCAN" and I get the prompt "NO CONNECTION". No rescan to bring blocks up to it's current block because there is no connection and therefore no access to my wallet. I have my seed phrase, but, that will not reconnect me to my wallet. I know that, because, I went to open a new wallet and it gives you two choices, you can open new wallet with new seed phrase or you can elect to recover your wallet with my seed phrase I already have. I have recovered my wallet using my seed phrase and recovered my account before so I know how it works. But, because I have NO CONNECTION, that page will not pop up and I get the two prompts, "NO CONNECTION" and ERROR: "Failed to fill whole buffer". I don't know how to recover my connection so I can recover my wallet. Please help me recover my connection. Below is an attachment that displays no connection to the Pirate Network.
Please respond to this email: swankm727o522@protonmail.com
Thank you, Charles Swank

![Screenshot_802](https://user-images.githubusercontent.com/65625306/208174714-e57cf695-a9b7-4856-83bd-144a517df585.png)

**Comment by sailorjerry58** [comment]
I am having the same issue.

**Comment by pepe8505** [comment]
como se resuelve este problema tengo el mismo problema ahora

**Comment by CryptoForge** [comment]
update to the newest version
