### ISSUE TITLE
Unable to send funds to different wallet

### ISSUE THREAD

**Issue by TrapToTrade** [PirateNetwork/PirateWallet-Lite#106]
Unable to send funds from pirate chain lite wallet app on Macbook to wallet on different exchange. 

Error message reads: Couldn't understand Response: {"error":"Error: SendResponse { error_code: -26, error_message: \"18: bad-txns-joinsplit-requirements-not-met\" }"}

**Comment by CryptoForge** [comment]
Rescan your wallet
