### ISSUE TITLE
Error: grpc-status: Internal, grpc-message: "Unexpected compression flag: 60"

### ISSUE THREAD

**Issue by shazza1959** [PirateNetwork/PirateWallet-Lite#107]
Hi all,
I tried to open my pirate lite wallet v1.0.6 yesterday and today. This error message came up also with no connection. Does anybody else have the same problem, Error: grpc-status: Internal, grpc-message: "Unexpected compression flag: 60"
I'm sorry if this issue has been posted before but i wasn't able to find it
Please can any one help? and thanks in advance

**Comment by Kinopisk** [comment]
Which your PC configuration and OS?

**Comment by Kinopisk** [comment]
**travlinpartner**, Which your PC configuration and OS?

**Comment by travlinpartner** [comment]
Sorry, Imac 2.5 GHz Intel Core i5, 8 Gigs ram, os High Sierra

**Comment by shazza1959** [comment]
Hi Kinopisk,
Sorry for the late response but been away. 
Im using Windows 11 Version 22621.1702
AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx     2.10 GHz
Im using a Dell inspiron 153000

I checked my pirate wallet earlier this year, about March i think and it was working fine then.
Any suggestions will be greatly appreciated :)

**Comment by CryptoForge** [comment]
update to the newest version
