### ISSUE TITLE
piratewallet-lite-v1.0.8 can't sync on the block 2422855

### ISSUE THREAD

**Issue by Kinopisk** [PirateNetwork/PirateWallet-Lite#108]
> There was an error sending the transaction. The error was:
> 
> Error: Error getting client: tonic::transport::Error(Transport, hyper::Error(Connect, Custom { kind: UnexpectedEof, error: "tls handshake eof" }))

**Comment by Tracex-sys** [comment]
Support, Charles Swank here; I have had many issues concerning my account in my lite wallet, one after another and the latest
one is depicted above: piratewallet-lite-v1.0.8 can't sync on the block 2422855 #108
There are over 59.xxxxxxx tokens missing, there should be about 1,038.xxxxxxxx tokens in my account over all. What is the problem? What are the issue's concerning Pirate.Black Lite Wallet. I'm getting nervous. See attachments below.
                                                                                       Please advise,
                                                                                       Charles Swank  (Tracex-sys)

Open
[Kinopisk](https://github.com/Kinopisk) opened this issue 2 weeks ago · 0 comments
There was an error sending the transaction. The error was: Error: Error getting client: tonic::transport::Error(Transport, hyper::Error(Connect, Custom { kind: UnexpectedEof, error: "tls handshake eof" })).
![Screenshot_523](https://github.com/PirateNetwork/PirateWallet-Lite/assets/65625306/d4b11a33-df28-470d-8f6d-0e63f8e9a6a7)
![Screenshot_524](https://github.com/PirateNetwork/PirateWallet-Lite/assets/65625306/39e03be8-e598-4031-9b73-04957894efa1)
![Screenshot_525](https://github.com/PirateNetwork/PirateWallet-Lite/assets/65625306/01287853-ae55-4361-8918-5bc3bc2f6806)

**Comment by CryptoForge** [comment]
update to the newest version
