### ISSUE TITLE
cant withdraw from TO

### ISSUE THREAD

**Issue by TaonaTool** [PirateNetwork/PirateWallet-Lite#11]
just tried to to some test runs and coins are not moving from TO to lite wallet.. Just wondering what side the issue is.. i kinda think its TO but i dont know.

**Comment by scott-fromthefuture** [comment]
I would assume TO, there has been quite a few reports of issues. I think they are overwhelmed with all the traffic lately. 

First thing to do is check the Txid in the https://explorer.pirate.black/. If the transaction shows on the blockchain, but not your wallet than there could be some issue, but if the txid is not on the blockchain it means TO has not yet sent it.
