### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by pugilas** [PirateNetwork/PirateWallet-Lite#110]
Error: grpc-status: Internal, grpc-message: "Unexpected compression flag: 60"
sgard@gmail.com

**Comment by TheComputerGenie** [comment]
This is the same as https://github.com/PirateNetwork/PirateWallet-Lite/issues/107

**Comment by pugilas** [comment]
no connection. Error message: Error: grpc-status: Internal, grpc-message: "Unexpected compression flag: 60"
please help me
