### ISSUE TITLE
ARRR balance is showing zero when its supposed to have 500+ ARRR PLEASE FIX!

### ISSUE THREAD

**Issue by austingotham** [PirateNetwork/PirateWallet-Lite#111]
I'm missing my ARRR in my lite wallet and it's supposed to have 500+ ARRR in it. I read online forums that this is a reoccurring issue and people keep having their wallets balance drop to zero. Devs please fix immediately and permanently! The ARRR price keeps dropping and my wallet isn't working I should've traded for btc or eth by now but the wallet bug hasn't been patched yet. hope it's fixed tonight.

**Comment by CryptoForge** [comment]
Update to the newest version and rescan
