### ISSUE TITLE
not able to upload my arr wallet..

### ISSUE THREAD

**Issue by chakaura** [PirateNetwork/PirateWallet-Lite#113]
Hi,
I am attempting to open my pirate wallet and i get the following message
Error: grpc-status: Internal, grpc-message: "Unexpected compression flag: 60"

Thank you for your support

**Comment by tejonmax1** [comment]
did you get yours working?  Mine is doing the same thing.
thanks

**Comment by chakaura** [comment]
no..any idea what to do?

Thank you for reaching out.

If you wish to book a session please contact the office. Thank you

Oshtalo

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by tejonmax1** [comment]
I haven't gotten mine to work yet either.  Thinking about installing the wallet on another computer and see if that works.

**Comment by tejonmax** [comment]
Did you get yours working?  I found a solution.  You need to download the 1.0.9 version.  I did that and it fixed the problem.  Before  that I did delete the old version and restarted it using my seed words and it still locked up before it was done syncing.  After downloading 1.0.9 it went all the way through the sync and is working great

**Comment by chakaura** [comment]
ok ill try that..thanks

Thank you for reaching out.

If you wish to book a session please contact the office. Thank you

Oshtalo

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by CryptoForge** [comment]
The server was down
