### ISSUE TITLE
Wallet syncing stuck at 2425855 block

### ISSUE THREAD

**Issue by bchtrue** [PirateNetwork/PirateWallet-Lite#116]
Wallet syncing stuck at 2425855 block

Each time I'm trying to sync (recovered wallet) it stuck at some block... Maybe always at this one...

**Comment by bchtrue** [comment]
at console: 
id: 1, batch: 0/61, blocks: 0/1000, decryptions: 0, tx_scan: 0
id: 1, batch: 0/61, blocks: 0/1000, decryptions: 0, tx_scan: 0
id: 1, batch: 0/61, blocks: 0/1000, decryptions: 0, tx_scan: 0
id: 1, batch: 0/61, blocks: 0/1000, decryptions: 0, tx_scan: 0
id: 1, batch: 0/61, blocks: 0/1000, decryptions: 0, tx_scan: 0
id: 1, batch: 0/61, blocks: 0/1000, decryptions: 0, tx_scan: 0

**Comment by bchtrue** [comment]
I think that issue related to connection lose... If you close / lose connection during syncing - it will stuck and not possible to continue... wallet will print only this lines

**Comment by bchtrue** [comment]
4 try to sync and always some error like this and not possible to end the sync: 
qt.qpa.xcb: QXcbConnection: XCB error: 8 (BadMatch), sequence: 2264, resource id: 20971556, major code: 42 (SetInputFocus), minor code: 0

**Comment by CryptoForge** [comment]
Update to the newest version
