### ISSUE TITLE
piratewallet-lite quit unexpectadely on Mac

### ISSUE THREAD

**Issue by Marrrrrrrrrtin** [PirateNetwork/PirateWallet-Lite#12]
Restarted the old Mac - wallet keeps shutting down when I try to send Arrr back to TO. 

Any suggestions?

**Comment by goldfingers777** [comment]
Same is happening to me any resolution yet?

**Comment by Marrrrrrrrrtin** [comment]
Apparently you can restore your wallet on Android with the seed phrase...will check it out

Ma Bu

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Bimbaland** [comment]
Same issue. I can restore wallet but only one address comes up out of three. Any help please? I am using High Sierra OSX
