### ISSUE TITLE
Pirate lite wallet not syncing  no control of wallet and 59.xxxxx still missing

### ISSUE THREAD

**Issue by Tracex-sys** [PirateNetwork/PirateWallet-Lite#123]
Pirate lite wallet not syncing  no control of wallet and 59.xxxxx still missing and no value of tokens displayed. 1.0.10 not working. Let's do it all over again using my seed phrase. What is the ongoing problem. I can't send or receive and account will not sync. I am loosing confidence in pirate chain and am afraid I will loose all tokens.

                                                                                                            Charles Swank

**Comment by Tracex-sys** [comment]
no connection to my wallet, no control over wallet.   charles swank

**Comment by CryptoForge** [comment]
Go to Telegram or Discord for support. I can help you better there.
