### ISSUE TITLE
Pirate Wallet Lite not showing any information

### ISSUE THREAD

**Issue by gregoryagogo** [PirateNetwork/PirateWallet-Lite#124]
It's as if I don't have any pirate coins.... but I do!

**Comment by gregoryagogo** [comment]
Not SYNCING

**Comment by CryptoForge** [comment]
upgrade your wallet, you are 6 versions out of date.

**Comment by gregoryagogo** [comment]
I t did finally work!

—Gregory
 

    On Thursday, September 14, 2023 at 10:07:01 PM PDT, CryptoForge ***@***.***> wrote:  
 
 


upgrade your wallet, you are 6 versions out of date.

**Comment by gregoryagogo** [comment]
SAYS I'VE GOT THE LATEST VERSION.



—Gregory
 

    On Thursday, September 14, 2023 at 10:07:01 PM PDT, CryptoForge ***@***.***> wrote:  
 
 


upgrade your wallet, you are 6 versions out of date.

**Comment by gregoryagogo** [comment]
![image](https://github.com/PirateNetwork/PirateWallet-Lite/assets/83630287/8238e401-ab89-4f3a-8070-dfc5f491ed4b)

**Comment by TheComputerGenie** [comment]
Update manually
https://github.com/PirateNetwork/PirateWallet-Lite/releases/tag/1.0.10
