### ISSUE TITLE
can't get my seed phrase

### ISSUE THREAD

**Issue by Puff501** [PirateNetwork/PirateWallet-Lite#127]
I need to export my passphrase but when I try to through the piratewallet lite v1.0.10, i click file, export seed phrase, then the window opens and I put in my password, and click ok and the wallet just freezes up.  The reason I need the seed is because Pirate is doing some Migration thing and I am having trouble migrating and I have to be sure I have my seed phrase correct.

Help

**Comment by xKOSIUSx** [comment]
There is no migration. You are talking to scammers. Make sure you are in the official Pirate channels/servers (you’re most likely in a fake Telegram server). Always check multiple official channels to verify this type of news.

I repeat again, THERE IS NO MIGRATION, YOU ARE BEING SCAMMED!

**Comment by Puff501** [comment]
OK I wasn't sure about that but thanks so forget the migration.  Is there a way I can get a new seed phrase for my wallet?

**Comment by kaks25** [comment]
You can reset the wallet to get a new wallet by renaming the "arrr-light-wallet.dat" to anything like "arrr-light-wallet-old.dat" which you can do it Via CMD(Windows) or Terminal (Linux/Mac), 

Note: you need to close the wallet first before the renaming the arrr-light-wallet.dat file


Linux(TERMINAL):
cd ~/.pirate; mv arrr-light-wallet.dat arrr-light-wallet-old.dat

Windows (CMD):
cd %appdata%\pirate & rename "arrr-light-wallet.dat" "arrr-light-wallet-old.dat"

Mac (Terminal):
cd ~/Library/Application\ Support/pirate; mv arrr-light-wallet.dat arrr-light-wallet-old.dat


Once you done it open the lite wallet you can create a new seedphrase or restoring the wallet with existing seedphrase

**Comment by Puff501** [comment]
Can I completely remove my pirate wallet and install it anew like it is my first day with no old data left?

**Comment by kaks25** [comment]
Sure

Linux(TERMINAL):
cd ~/.pirate; rm arrr-light-wallet.dat

Windows (CMD):
cd %appdata%\pirate & del arrr-light-wallet.dat

Mac (Terminal):
cd ~/Library/Application\ Support/pirate; mv arrr-light-wallet.dat

**Comment by Puff501** [comment]
OK, I seem to have my new wallet set up with new seeds and passwords and I'm testing now sending some Pirate back and forth from TO.  My question now is when I used to send anything from my wallet, I would get a verification window where I'd have to enter my password to initiate the send.  Now wallet just sends without this password verification.  How do I get it to ask for this verification before the wallet actually sends?

**Comment by kaks25** [comment]
Go to Edit > Encrypt Wallet

**Comment by Puff501** [comment]
Thanks for your help guys.  All seems good now.
