### ISSUE TITLE
ARRR has not deposited into TradeOgre

### ISSUE THREAD

**Issue by Puff501** [PirateNetwork/PirateWallet-Lite#15]
Tried to make a deposit from Pirate Wallet Lite to TradeOgre
I followed the transaction instructions and the transaction seemed to go smoothly however the deposit has not appeared in TradeOgre.
I only sent a small amount, 5 AAAR, as a test to make sure it would make it and I'm glad I did.
I will attach documentation to assist you in tracking where the problem may be.
I am using windows 10 64 bit, MIcrosoft Edge Version 90.0.818.42 (Official build) (64-bit).
I really think the problem is not with my hardware.
Thank You
Steve
![block](https://user-images.githubusercontent.com/82999722/115949304-f651de00-a488-11eb-8649-782893043ba1.JPG)
![deposit](https://user-images.githubusercontent.com/82999722/115949331-4a5cc280-a489-11eb-90fa-df93c18ce237.JPG)
If you need any other info, please ask.

**Comment by scott-fromthefuture** [comment]
please correct me if I am wrong, but is that not a screenshot of the Tx showing it was sent, received by the network, and included in the block? 

It would seem everything worked as expected. Looks like the issue is the Trade Ogre is not showing the balance as received. I am assuming they have gotten much more traffic than they are prepared for. Have you spoken with them yet?

**Comment by Puff501** [comment]
Yes that is what I thought too, that the screenshot showed all went well.
Contacted T/O through Twitter account and the answer was ARRR wallet slowly processing.
Screenshot enclosed.
It's been about 15 hours now and still hasn't shown up.
If you have better contact info for T/O other than the Twitter account, would you please attach it?
Thank You
![TOTwitter](https://user-images.githubusercontent.com/82999722/115961246-7cdadf80-a4ca-11eb-88a6-8e7bfe0683b5.JPG)

**Comment by Puff501** [comment]
Follow up ...
ARRR showed up in T/O account finally.  Total time was 18 hours to complete transfer.
