### ISSUE TITLE
Can Send Pirate Chain from Tradeogre to Wallet Lite

### ISSUE THREAD

**Issue by Lost-in-the-ETH** [PirateNetwork/PirateWallet-Lite#17]
Traded BTC for Pirate Chain on Tradeogre.  Tried to transfer to my pirate chain wallet lite and first transfer failed after about an hour of processing.  Tried a second time and it has been stuck in processing for over two hours. 

Windows, Chrome Version 90.0.4430.85 (Official Build) (64-bit)
Pirate Chain Wallet Lite Version 1.0.4

**Comment by teoman002** [comment]
Wouldn't this be a problem with the TradeOgre exchange? Find their contact address and ask them if they can cancel the transaction and start a new one. They need your account details, transaction details and wallet address, do not send them passwords.
