### ISSUE TITLE
Error message while generating seed

### ISSUE THREAD

**Issue by ghost** [PirateNetwork/PirateWallet-Lite#2]
I ran the lite wallet on Linux offline and when choosing to create a new wallet, the following error message pops up inside the window where the seed should appear:

Error creating a wallet
Error: failed to lookup address information: Name or service not known

Device is Linux Mint 20.1 Cinnamon.

**Comment by robster7674** [comment]
Same here, on macOS however. It seems counterintuitive from a security point of view to having to be online when generating a seed phrase that shows on-screen.
