### ISSUE TITLE
Wallet empty and does not sync

### ISSUE THREAD

**Issue by TorinoLTD** [PirateNetwork/PirateWallet-Lite#21]
Since 3 days ago I have uninstalled and reinstalled the Pirate lite wallet and entered my pass phrases and to no avail... the wallet does not show a compete sync nor does it show my assets in the wallet... every thing is blank.
Even went online to see if problem has happened to others and saw how to rename .dat file so it would ask for pass phrase again... did that and still nothing... 
What gives????

**Comment by igordemydczuk** [comment]
did you solve the it? I have the same problem...

**Comment by TorinoLTD** [comment]
You have to remove all traces of the program and reinstall it , then when
you restore the wallet you CANNOT use 0 as the starting point for sync...
When you were trying before it gave you a chain sync location like
135287/1378256  What I did was picked a number above the lower number and
it took about 10 minutes to update the blockchain location and restore the
wallet.

Was a guess that worked because I felt the Sync was hanging up somewhere on
the blockchain between 0 and the lower number..

Give it a shot.

**Comment by igordemydczuk** [comment]
Thank you for the answer…
What do you mean  by;
‘…Cannot use 0 as a starting point for sync?
How / what / where from, did you pick a number above the lower number? 
I have no idea what do you mean by that..


Igor Demydczuk
E: ***@***.***
W: www.igordemy.com
F: Igor D-Creativist

**Comment by TorinoLTD** [comment]
When restoring the wallet with you pass phrase it says to enter your
origin blockchain location number.... unfortunately I did not record that
when I set up my wallet... If you did then just enter that number...
It says that if you do not know the original number then just leave at 0 ,
however this has not worked because it hangs somewhere in the Sync process
and will not complete.
So I just picked a blockchain location number above the lower number that I
saw when the sync process failed and below the highest blockchain number
and it worked.... took some time for the sync to go thru the blockchain but
it pulled everything back into the wallet.
Hope this helps.

**Comment by igordemydczuk** [comment]
Thank you very much for your time helping me with it. I have saved my key words and my privet key, so I guess I will not have the problem…
However, there was announcement that the Piret chain team are upgrading the system, which is causing theis problem… So I just wait for this to be solved first… 
For the rest I will remember what to do for the future problems…
many thanx bro,
Cheers from Holland...


Igor Demydczuk
E: ***@***.***
W: www.igordemy.com
F: Igor D-Creativist

**Comment by TorinoLTD** [comment]
Most welcome and here is to protecting our privacy and our freedom...
From up in the mountains of North Carolina USSA   😊

**Comment by igordemydczuk** [comment]
Thanx!
Freedom is what that is all about, isn’t it?
Here in Europe we are quite polarised… 
The half which is recognising the real issue of taking the freedom away from the people,
 is fighting hard and we are prepare to fight all the way my friend...
because there is nothing after that being taking away from us!
Love & peace..


Igor Demydczuk
E: ***@***.***
W: www.igordemy.com
F: Igor D-Creativist

**Comment by TorinoLTD** [comment]
Agree totally Brother
Love & Peace
