### ISSUE TITLE
Issue Sending 

### ISSUE THREAD

**Issue by mikaylahieber** [PirateNetwork/PirateWallet-Lite#26]
Hey! I love ARRR. Just downloaded PirateWallet-Lite and successfully transferred my Pirate Chain into the wallet. However, I am now trying to send some ARRR to another platform and the PirateWallet-Lite app is quitting unexpectedly. I noticed it yesterday and it's still happening this evening. It would be amazing amazing if you could help me.

**Comment by teoman002** [comment]
Hey, I am not a dev but I can help you.

Let us first collect the information about your situation:

- Which Operating System are you using?
- Did you write down your personal recovery word list during wallet creation? Have it ready in a safe location to recover your wallet!

You could try this:

- Use another operating system on the same computer, ubuntu-live on usb or dvd?
- Use another computer to open the lite wallet
- Use the recovery phrase to recover your wallet on a different system
