### ISSUE TITLE
Lite wallet shutting down

### ISSUE THREAD

**Issue by krisg-sketch** [PirateNetwork/PirateWallet-Lite#28]
Please help, I want to send some ARRR out of my Lite wallet, and as soon as I hit OK in the final step ( confirmation), wallets shuts down: message Crashed Thread:        4  Thread (pooled)

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Dyld Error Message:
  Symbol not found: ____chkstk_darwin

**Comment by brandon954** [comment]
Having same issues, would like some more info regarding this matter. Thank you

**Comment by krisg-sketch** [comment]
Issue with CPU/OS on Mac- too old and too slow, need to re load on Windows
based PC or Mac OS catalina
