### ISSUE TITLE
PirateWallet-Lite (Error message)

### ISSUE THREAD

**Issue by ajv87** [PirateNetwork/PirateWallet-Lite#40]
Hi,

I have a problem with my PirateWallet-Lite that don't allow me to access my wallet. When I start the application there is an error message as follow:

Transaction Error
There was an error sending the transaction. The error was:
Server's latest block(518377) is behind ours(1373053)

![Capture](https://user-images.githubusercontent.com/83619131/116946137-5eea4900-ac47-11eb-897f-e6af38b05426.JPG)

Please help me, 
thank you in advance.
Jairo

**Comment by Puff501** [comment]
Jairo, I'll jump on your problem because I am having the same one just with different block numbers.
Windows 10, Microsoft Edge
Steve
![wallet](https://user-images.githubusercontent.com/82999722/116948198-a1a22600-ac33-11eb-9f87-64bc781aeecf.JPG)

**Comment by ajv87** [comment]
yeah Steve, same OS here, W10 Home.

**Comment by a2zboss** [comment]
oi have same problem different block number and our number.

**Comment by ohnojerryfell** [comment]
same issue Mac OS                        There was an error sending the transaction. The error was:

Server's latest block(541371) is behind ours(1371538)

**Comment by eyeonfashion** [comment]
Pirate wallet lite problem to access.
using Windows,  error as per photo -->

![pirate wallet error](https://user-images.githubusercontent.com/83624655/116955443-88639e80-ac60-11eb-847b-86309a1508e9.PNG)

**Comment by Supermike7** [comment]
Glad i'm not the only one! Same problem after small send to TradeOgre. ERROR 
Please inform me if you get a fix. Thanks All

**Comment by BARTEKES13** [comment]
I just read this ,probably it has to do with this ,Our Lite Wallet servers had another huge surge of demand and are now being upgraded again. 🏴‍☠️

Please bear with us as are making these changes and rest assured that your funds are safe.

The changes will affect both the lite wallet desktop version and the mobile wallet.

**Comment by Supermike7** [comment]
Seems to be ok now. Thank You to all responsible!

**Comment by ajv87** [comment]
> I just read this ,probably it has to do with this ,Our Lite Wallet servers had another huge surge of demand and are now being upgraded again. 🏴‍☠️
> 
> Please bear with us as are making these changes and rest assured that your funds are safe.
> 
> The changes will affect both the lite wallet desktop version and the mobile wallet.

It works now, thank you

**Comment by Supermike7** [comment]
Thank You! Great work? Much appreciated.
