### ISSUE TITLE
can't access wallet

### ISSUE THREAD

**Issue by a2zboss** [PirateNetwork/PirateWallet-Lite#41]
I can't access wallet I keep getting error  ... there was an error sending the transaction. The Error was: Server's latest block (539411) is behind ours.

**Comment by ohnojerryfell** [comment]
same issue Mac OS There was an error sending the transaction. The error was:

Server's latest block(541371) is behind ours(1371538)

**Comment by dareso86** [comment]
i had a same problem

**Comment by Ahtel** [comment]
I have the same issue.  Tried opening wallet several times and got same error message "Latest block (insert number) as they were always different is behind block 1372413.
