### ISSUE TITLE
error with logging onto my piratelite wallet

### ISSUE THREAD

**Issue by jakemate16** [PirateNetwork/PirateWallet-Lite#46]
there's a login error saying "There was an error sending the transaction. The error was:

Server's latest block(589564) is behind ours(1373346)" 
help would be appreciated thanks 
jake

**Comment by BARTEKES13** [comment]
yes,indeed,same with me and many others ,it seems they have some problems .this is not good.I read many reports of this error but no reply .It seems pirate chain is not yet ready ,they can not deliver what they promise
