### ISSUE TITLE
Pirate Wallet lite  v 1.0.4

### ISSUE THREAD

**Issue by cryptopoli** [PirateNetwork/PirateWallet-Lite#49]
Transaction ERROR

There was an error sending the transaction. The error was:

Server's latest block(610282) is behind ours(1373304

Resacan blocket!

What can I do?

**Comment by mlchaelmlchael** [comment]
I have exactly the same issue

**Comment by cryptopoli** [comment]
Can Verus Wallet Pirate native be open in parallel with Pirate Wallet Lite?

**Comment by mlchaelmlchael** [comment]
Sorry I have no idea, I'm waiting for the support team to get back to me too on what seems to be effecting a number of people
