### ISSUE TITLE
Balance Not Showing Up in PirateWallet Lightclient

### ISSUE THREAD

**Issue by Extremed** [PirateNetwork/PirateWallet-Lite#50]
As of Tuesday, May 4, 2021, 5:21am, My PirateWallet Lightclient v1.04 I get the message:

There was an error sending the transaction.  The error was:
Server's latest block(647215) is behind ours(1371363)

I double-checked this account on the Ghostship OS that also runs PirateWallet Lightclient.
It synced up to all the blocks and gave no error - but - SHOWED a balance of ZERO too!
![Selection_587](https://user-images.githubusercontent.com/33352272/116990564-e9a76400-ac98-11eb-8e42-01038ab9b894.png)

**Comment by SueAP** [comment]
Same problem. I hope someone from the Pirate team says something soon.

**Comment by bobdobalina33** [comment]
Anyone get any answers?
