### ISSUE TITLE
Big problems with my lite wallet 

### ISSUE THREAD

**Issue by SueAP** [PirateNetwork/PirateWallet-Lite#51]
I cannot see my ARRR´s. 
When I try to open my wallet It says no conexion and afterwards it shows the following message:  
[error lite wallet.pdf](https://github.com/PirateNetwork/PirateWallet-Lite/files/6420679/error.lite.wallet.pdf)

Please can you help us? 
Best regards,

**Comment by SueAP** [comment]
Server's latest block(660417) is behind ours(1366245)

**Comment by dareso86** [comment]
i have same problem can someone help us ?

**Comment by Cryptobiz88** [comment]
Likewise..I had the same problem and of course no ARRR's and now i have this message:

Error: grpc-status: Internal, grpc-message: "Unexpected compression flag: 60"

**Comment by SueAP** [comment]
I received a message from some from Marketing from the Pirate platform:
"Dear Susana,

Our Lite Wallet servers had another huge surge of demand and are now being upgraded again.
Please bear with us as we are making these changes and rest assured that your funds are safe.
The changes will affect the lite wallet for desktop and the mobile wallet.
 Kind regards,

KOSIUS
