### ISSUE TITLE
transaction error - lite wallet on PC,..  how to fix? thanks 

### ISSUE THREAD

**Issue by myibiza** [PirateNetwork/PirateWallet-Lite#53]
transaction error - lite wallet on PC,..  how to fix? thanks 

![ARRR_error](https://user-images.githubusercontent.com/83651598/117009216-cc4fb580-aceb-11eb-906d-47bfb9824fbc.JPG)

**Comment by Slyshot247** [comment]
![Pirate wallet](https://user-images.githubusercontent.com/36980892/117017082-f0de6a00-acb8-11eb-8e5f-b8ad95b4293e.PNG)
I got similar error

**Comment by myibiza** [comment]
yes i see that!

i wonder what it is?

lets wait for someone from pirate to answer us!

**Comment by myibiza** [comment]
new error:


![ARRR_error2](https://user-images.githubusercontent.com/83651598/117031257-af71ad00-ad00-11eb-8535-8c3520da9835.JPG)

**Comment by MadMaxMarie** [comment]
I am having the same issue with my wallet, I hope we get answers soon & glad I am not the only one. 
![Screen Shot 2021-05-04 at 10 58 26 AM](https://user-images.githubusercontent.com/83661318/117034557-0cea0780-acc9-11eb-87da-720c06190ccb.png)

**Comment by BARTEKES13** [comment]
message from twitter , Our Lite Wallet servers had another huge surge of demand and are now being upgraded again.  Piratenvlag

Please bear with us as we are making these changes and rest assured that your funds are safe. 

The changes will affect the lite wallet for desktop and the mobile wallet.

**Comment by myibiza** [comment]
ahh great thanks!

we wait then

ARRR!
