### ISSUE TITLE
Error: grpc-status: Internal, grpc-message: "Unexpected compression flag: 60"

### ISSUE THREAD

**Issue by scottmccrtny** [PirateNetwork/PirateWallet-Lite#55]
error: grpc-status: Internal, grpc-message: "Unexpected compression flag: 60" 

New wallet error message.

**Comment by scottmccrtny** [comment]
my bad

**Comment by jcalfee** [comment]
I'm investigating this, thanks for posting it.  Was it just a network connection error?
