### ISSUE TITLE
Am I synced?

### ISSUE THREAD

**Issue by kthorlakr** [PirateNetwork/PirateWallet-Lite#8]
"Synced 152855 / 1358051"   

just frozen on startup and syncing on all platforms and multiple workstations.

**Comment by jatarrrr** [comment]
I have  the same problem,  at 152877/ 1359176.  Says "not connected" and I cannot access my lite wallet on any platform.

**Comment by scott-fromthefuture** [comment]
What OS are you on? I am not a Pirate dev, but I once had an issue with the dat file. On Ubuntu it is located in ~/.pirate/arr-lite-wallet.dat. BE SURE TO BACKUP. Make a copy if there are funds and be sure your seed phrase is properly saved if you want to restore the wallet later. You can delete the dat file, uninstall the wallet, and download/install a fresh copy.

Before you do, you may try clicking edit in the toolbar and selecting rescan to see if it helps. I have running on a few devices with no issues so I am unable to reproduce

**Comment by TorinoLTD** [comment]
Same problem... no results from re installing...

**Comment by scott-fromthefuture** [comment]
It looks like a couple of people have had a similar issue that was resolved. I would recommend having a look at the #wallets support channel on the discord. https://discord.gg/JEkDzBADx2
