### ISSUE TITLE
$ not getting to my Pirate Chain wallet

### ISSUE THREAD

**Issue by JeffGwi** [PirateNetwork/PirateWallet-Lite#85]
I recently sent a small amount of Pirate Chain from TradeOgre to my Pirate Chain Lite wallet. It has been 6 hours and I haven't received the Pirate Chain. What should I do? It showed up as "Successful" on TradeOgre.

**Comment by Pheasant123** [comment]
I had a similar experience with Coinex and when I looked at the chain explorer it showed and invalid address for the transaction.  I used the wallet generated address.
