### ISSUE TITLE
RE: can't send Pirate Chain from my lite wallet 

### ISSUE THREAD

**Issue by Suzanne4sure** [PirateNetwork/PirateWallet-Lite#86]
So I am able to put in the address, and another form pops up, confirming the from/to addresses, and the miner fee, but it never allows for confirmation.  I have tried reducing the screen, but the confirmation page, never reduces properly, to where I assume is a button to confirm the send/to and acceptance of the miner fee, at the bottom of the confirmation page exists.

**Comment by justkitc** [comment]
Did you get this resolved, have the same issue
