### ISSUE TITLE
wallet is empty

### ISSUE THREAD

**Issue by ferndalecarl** [PirateNetwork/PirateWallet-Lite#92]
I transferred ARRR to a wallet around May 2020 and initially it worked great and I was able to see the balances in my wallet, but after some months the balance was gone completely.  I tried freshly downloading every type of wallet including Lite and recovering from seed phrase but nothing seems to work, the balance is still zero.  The only hint I have that it is the correct wallet is that the transfer addresses are still in the address book.  When I run a history report it is completely blank.  Any help is most appreciated, Thanks!

**Comment by bobdobalina33** [comment]
Did you ever figure out the issue?  Im dealing with the same thing rn.  Wallet is empty.

**Comment by ferndalecarl** [comment]
Hello yes I did fix it.  I found some detailed instructions in a Reddit
post.  the biggest issue I had was that I had the coins in three separate
wallets, which we're not appearing, and essentially had to be re-added.
The Reddit post detailed how if you generate a new address, the first few
addresses will be exactly your wallet addresses.  After generating the
addresses (which were in fact my exact wallet addresses) I refreshed
everything and my coins appeared again.  I'm sorry I don't know the exact
address to the red post but I'm sure you could find it by googling.  Best
of luck!
