### ISSUE TITLE
Lightclient v1.0.4 Doesn't Sync

### ISSUE THREAD

**Issue by McFuhr** [PirateNetwork/PirateWallet-Lite#95]
I have Lightclient v1.0.4 it doesn't sync. And I'm unable to load the latest version. Do I have to download the newest version and restart with seed

**Comment by bobdobalina33** [comment]
Yea Im having same issue.  As of now when I open the wallet, theres nothing in it.  And Im kind of trippin.

**Comment by McFuhr** [comment]
It working now. All synced. Might be a busy network for syncing.  I had issues like this in the past. Yours should be syncing now.
